import Footer from '@components/footer/Footer';
import Navbar from '@components/navbar/Navbar';
import '@styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='min-h-screen'>
        <Navbar />
        <main className='mt-[70px]'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
